name: my first Workflow
on:
  push:
    branches:
      - main
jobs:
  gadpp_job:
    name: My first job in workflow for github actions
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world!"
      - shell: bash
        run: |
          date > output.log
      - shell: bash
        run: |
          df -h
          lsblk
          uname -a
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Push updates to your profile page
#        uses: umutphp/github-action-dynamic-profile-page@v2
#        id: gadpp
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          github-username: 'dat-adi'
#          user-email: 'dat.adithya@gmail.com'
